name: wa_inventory
description: A Flutter Firebase Inventory Management App
# Last updated: February 2024 - Enhanced with latest dependencies
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  go_router: ^10.0.0
  image_picker: ^1.0.2
  charts_flutter: ^0.12.0
  fl_chart: ^0.63.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.2.6
  flutter_slidable: ^3.0.0
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/inventory.png
    - assets/images/inventorylist.png
    - assets/images/report.png
    - assets/images/stockout.png
    - assets/images/shoe1.jpg
    - assets/images/login.png
    - assets/images/register.png
    - assets/images/splesh.png
