/*
 * Last Updated: February 2024
 * Firebase configuration options for the application
 */

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7HDf5ScEvQwvmf-3tKtJi5MUla5bA10c',
    appId: '1:962597248401:web:bd3ece56b9f229c3fece30',
    messagingSenderId: '962597248401',
    projectId: 'inventory-management-app-38c45',
    authDomain: 'inventory-management-app-38c45.firebaseapp.com',
    storageBucket: 'inventory-management-app-38c45.firebasestorage.app',
    measurementId: 'G-FVCFDR83BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7HDf5ScEvQwvmf-3tKtJi5MUla5bA10c',
    appId: '1:962597248401:android:bd3ece56b9f229c3fece30',
    messagingSenderId: '962597248401',
    projectId: 'inventory-management-app-38c45',
    storageBucket: 'inventory-management-app-38c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7HDf5ScEvQwvmf-3tKtJi5MUla5bA10c',
    appId: '1:962597248401:ios:bd3ece56b9f229c3fece30',
    messagingSenderId: '962597248401',
    projectId: 'inventory-management-app-38c45',
    storageBucket: 'inventory-management-app-38c45.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.wa_inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7HDf5ScEvQwvmf-3tKtJi5MUla5bA10c',
    appId: '1:962597248401:macos:bd3ece56b9f229c3fece30',
    messagingSenderId: '962597248401',
    projectId: 'inventory-management-app-38c45',
    storageBucket: 'inventory-management-app-38c45.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.wa_inventory',
  );
}
