// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzD0vgicbevKRM_YqMK3p5G0YRo13yQtY',
    appId: '1:133953173361:web:173549d7c7fca98ca8e8d0',
    messagingSenderId: '133953173361',
    projectId: 'inventory-mgmt-app',
    authDomain: 'inventory-mgmt-app.firebaseapp.com',
    storageBucket: 'inventory-mgmt-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5N2_gNFrHuNRoY4PBvSakbuOLaXlc5c0',
    appId: '1:133953173361:android:68a1b16ffd6eca54a8e8d0',
    messagingSenderId: '133953173361',
    projectId: 'inventory-mgmt-app',
    storageBucket: 'inventory-mgmt-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyE3RWD9awtCl3YxowRp1chU-DWiTB1xc',
    appId: '1:133953173361:ios:fff9b3914d120147a8e8d0',
    messagingSenderId: '133953173361',
    projectId: 'inventory-mgmt-app',
    storageBucket: 'inventory-mgmt-app.appspot.com',
    iosBundleId: 'com.example.waInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7FuW9UOqzKTwXVrm8qtqaqjcMRAVkx6M',
    appId: '1:82436170302:ios:c132d0b12014b0f461676f',
    messagingSenderId: '82436170302',
    projectId: 'dan-energy-inventory-app',
    storageBucket: 'dan-energy-inventory-app.appspot.com',
    iosClientId:
        '82436170302-vcf2s41itf3kc80l6agp7tjvo4phtspj.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventory.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzD0vgicbevKRM_YqMK3p5G0YRo13yQtY',
    appId: '1:133953173361:web:a4130b8ee4d3847fa8e8d0',
    messagingSenderId: '133953173361',
    projectId: 'inventory-mgmt-app',
    authDomain: 'inventory-mgmt-app.firebaseapp.com',
    storageBucket: 'inventory-mgmt-app.appspot.com',
  );

}